export const constant = {
    PROVINCES : ['Kinshasa', 'Bas-Uele','Equateur','Haut Katanga','Haut Lomami','Haut-Uele','Ituri','Kassaï','Kassaï Oriental','Kassaï Central',
    'Kongo-Central','Kwilu','Kwango','Lomami','Lualaba','Mai-Ndombe','Maniema','Mongala','Nord-Kivu','Nord-Ubangi','Sankuru',
  'Sud-Kivu','Sud Ubangi','Tanganyika','Tsopo','Tsuapa'],

  VILLES: ['Bandundu','Baraka','Beni','Boende','Boma','Bukavu','Bunia','Buta','Butembo','Gbadolite','Gemena','Goma',
  'Inongo','Isiro','Kabinda','Kalemie','Kamina','Kananga','Kenge','Kikwit','Kindu','Kisangani',
  'Kinshasa','Kolwezi','Likasi','Lisala','Lubumbashi','Lusambo',
  'Matadi','Mbujimayi','Muene-Ditu','Tshikapa','Uvira','Zongo'],

  ROLES: ['ROOT','DG','DSI','COMMMERCIAL','PROVINCIAL','PAYMENT'],
  TYPE_CLIENT: ['ONG','FONDATION','SOCIETE PRIVE','EGLISE','SOCIETE PUBLIQUE','INDIVIDU'],
  ACTIVITE: ['AGRO-ALIMENTAIRE','TECHNOLOGIE','TELEVISION','TELECOMMUNICATIONS','AGRONOMIE',
  'SERVICES GENERAUX','EDUCATION','MARKETING']

}

export const  provinceData =
  [
    {
      name:"TSHOPO",
      villes:[
        "KISANGANI"
      ],
      territoires:[
        "Bafwasende",
        "Banalia",
        "Basoko",
        "Isangi",
        "Opala",
        "Ubundu",
        "Yahuma"
      ],
    },
    {
      name:"EQUATEUR",
      villes:[
        "MBANDAKA"
      ],
      territoires:[
        "Basankusu",
        "Bikoro",
        "Bolomba",
        "Bomongo",
        "Ingende",
        "Lukolela",
        "Mankanza"
      ]
    },
    {
      name:"MONGALA",
      villes:[
        "BUMBA"
      ],
      territoires:[
        "Bongandanga",
        "Bumba",
        "Lisala"
      ]
    },
    {
      name:"ITURI",
      villes:[
        "BUNIA"
      ],
      territoires:[
        "Aru",
        "Djugu",
        "Irumu",
        "Mahagi",
        "Mambasa"
      ]
    },
    {
      name:"TSHUAPA",
      villes:[
        "BOENDE"
      ],
      territoires:[
        "Befale",
        "Boende",
        "Bokungu",
        "Djolu",
        "Ikela",
        "Monkoto"
      ]
    },
    {
      name:"KWILU",
      villes:[
        "BANDUNDU",
        "KIKWIT"
      ],
      territoires:[
        "Bagata",
        "Bulungu",
        "Gungu",
        "Idiofa",
        "Masi-Manimba"
      ]
    },
    {
      name:"KWANGO",
      villes:[

      ],
      territoires:[
        "Feshi",
        "Kahemba",
        "Kasongo-Lunda",
        "Kenge",
        "Popokabaka"
      ]
    },
    {
      name:"MAI-NDOMBE",
      villes:[
        "INONGO"
      ],
      territoires:[
        "Bolobo",
        "Inongo",
        "Kiri",
        "Kutu",
        "Kwamouth",
        "Mushie",
        "Oshwe",
        "Yumbi"
      ]
    },
    {
      name:"KINSHASA",
      villes:[
        "KINSHASA"
      ],
      territoires:[
        "Gombe",
        "Kinsambu",
        "Ngaliema",
        "Mont Ngafula",
        "N'Djaba",
        "Lemba",
        "Matete",
        "Limeté",
        "Linguala",
        "Kinshasa",
        "Barumbu",
        "Masiina",
        "Kimbaseke",
        "N'sele",
        "N'Djili",
        "N'Djili-ndili",
        "Selembao",
        "Makala",
        "Kalamu",
        "Kasavubu",
        "Bumbu",
        "Ngiri-Ngiri",
        "Bandalungua",
        "Maluku"
      ]
    },
    {
      name:"SUD-UBANGI",
      villes:[
        "ZONGO",
        "GEMENA"
      ],
      territoires:[
        "Budjala",
        "Gemena",
        "Kungu",
        "Libenge"
      ]
    },
    {
      name:"NORD-UBANGI",
      villes:[
        "GBADOLITE"
      ],
      territoires:[
        "Bosobolo",
        "Businga",
        "Mobayi-Mbongo",
        "Yakoma"
      ]
    },
    {
      name:"SANKURU",
      villes:[
        "LUSAMBO"
      ],
      territoires:[
        "Katako-Kombe",
        "Kole",
        "Lodja",
        "Lomela",
        "Lubefu",
      ]
    },
    {
      name:"MANIEMA",
      villes:[
        "KINDU"
      ],
      territoires:[
        "Kabambare",
        "Kailo",
        "Kasongo",
        "Kibombo",
        "Lubutu",
        "Pangi",
        "Punia"
      ]
    },
    {
      name:"NORD-KIVU",
      villes:[
        "BENI",
        "BUTEMBO",
        "GOMA"
      ],
      territoires:[
        "Beni",
        "Lubero",
        "Masisi",
        "Nyiragongo",
        "Rutshuru",
        "Walikale"
      ]
    },
    {
      name:"SUD-KIVU",
      villes:[
        "BAKARA",
        "BUKAVU",
        "UVIRA"
      ],
      territoires:[
        "Fizi",
        "Idjwi",
        "Kabare",
        "Kalehe",
        "Mwenga",
        "Shabunda",
        "Uvira",
        "Walungu"
      ]
    },
    {
      name:"HAUT-KATANGA",
      villes:[
        "LUBUMBASHI",
        "LIKASI",
        "KIPUSHI"
      ],
      territoires:[
        "Kambove",
        "Kasenga",
        "Kipushi",
        "Mitwaba",
        "Pweto",
        "Sakania"
      ]
    },
    {
      name:"LUALABA",
      villes:[
        "KOLWESI"
      ],
      territoires:[
        "Dilolo",
        "Kapanga",
        "Lubudi",
        "Mutshatsha",
        "Sandoa"
      ]
    },
    {
      name:"HAUT-LOMAMI",
      villes:[
        "KAMINA"
      ],
      territoires:[
        "Bukama",
        "Kabongo",
        "Kamina",
        "Kaniama",
        "Malemba-Nkulu"
      ]
    },
    {
      name:"BAS-UELE",
      villes:[
        "BUTA"
      ],
      territoires:[
        "Aketi",
        "Ango",
        "Bambesa",
        "Bondo",
        "Buta",
        "Poko"
      ]
    },
    {
      name:"HAUT-UELE",
      villes:[
        "ISIRO"
      ],
      territoires:[
        "Dungu",
        "Faradje",
        "Niangara",
        "Rungu",
        "Wamba",
        "Watsa"
      ]
    },
    {
      name:"KASAI",
      villes:[
        "TSHIKAPA"
      ],
      territoires:[
        "Ilebo",
        "Kamonia",
        "Luebo",
        "Mweka",
        "Dekese"
      ]
    },
    {
      name:"KASAI-CENTRAL",
      villes:[
        "KANANGA"
      ],
      territoires:[
        "Dibaya",
        "Demba",
        "Dimbelenge",
        "Kazumba",
        "Luiza"
      ]
    },
    {
      name:"KASAI-ORIENTAL",
      villes:[
        "MBUJI-MAYI"
      ],
      territoires:[
        "Tshilenge",
        "Katenda",
        "Lupatapa",
        "Kabeya-Kamwanga",
        "Miabi"
      ]
    },
    {
      name:"KONGO-CENTRAL",
      villes:[
        "MATADI",
        "BOMA",
        "MBANZA-NGUNGU"
      ],
      territoires:[
        "Kasangulu",
        "Kimvula",
        "Lukula",
        "Luozi",
        "Madimba",
        "Mbanza-Ngungu",
        "Moanda",
        "Seke-Banza",
        "Songololo",
        "Tshela"
      ]
    },
    {
      name:"LOMAMI",
      villes:[
        "KABINDA",
        "NGANDAJIKA",
        "MWENE-DITU"
      ],
      territoires:[
        "Kabinda",
        "Kamiji",
        "Lubao",
        "Luilu",
        "Ngandajika"
      ]
    },
    {
      name:"TANGANYIKA",
      villes:[
        "KALEMIE"
      ],
      territoires:[
        "Kabalo",
        "Kalemie",
        "Kongolo",
        "Manono",
        "Moba",
        "Nyunzu"
      ]
    }
  ]
