{
      name:"TSHOPO",
      code:"12",
      villes:[
        {
          nom:"KISANGANI",
          code:"12",
          commune:[
            "TEST",
            "TEST"
          ]
        },
        {
          nom:"ZAMBA",
          code:"12",
          commune:[
            "TEST",
            "TEST"
          ]
        }
        
      ],
      territoires:[
        {
          nom:"Bafwasende",
          code:"12"
        },
        {
          nom:"TEST",
          code:"12"
        }
      ],
      proveds:[
        {
          nom:"TEST",
        code:"12",
        sousproveds:[
          {
            nom:"TEST",
            code:"12"
          },
          {
            nom:"TEST",
            code:"12"
          }
        ]
      },
      {
        nom:"TEST",
      code:"12",
      sousproveds:[
        {
          nom:"TEST",
          code:"12"
        },
        {
          nom:"TEST",
          code:"12"
        }
      ]
    }
      ]
    }